### PR TITLE
try to block image uploads > 10mb, before uploading

### PR DESCRIPTION
**Pull request by jcs**
a quick solution for issue #33

### CODE REVIEW

**Comment by jcs** [comment]
ok.  though technically if the post limit is a hard 8mb, a file of 8mb plus the other post data would exceed that.  it'd probably be better to just crank post/file upload limits to something sizable like 10mb (imgur's upload limit, btw) and enforce a smaller limit in the javascript.

**Comment by nyetwurk** [comment]
@jcs agreed, but I want to minimize the amount of work on the part of the admin installing kawf... perhaps make it dynamic depending on the configured php limit? Not sure of the variable, i'd have to look it up.

**Comment by nyetwurk** [comment]
ini_get('post_max_size');
ini_get('upload_max_filesize');

There is also the apache limit, which I'm not sure we can get in php.

**Comment by jcs** [comment]
yuck

**Comment by nyetwurk** [comment]
HA HA. Ugly, but hey, what else can you do

**Pull request merged**
