### PR TITLE
add option for relative timestamps on the thread index

### PR DESCRIPTION
**Pull request by jcs**

### CODE REVIEW

**Comment by jcs** [comment]
is wayot's database server returning a different time for `now()` than php's `time()`?

**Comment by nyetwurk** [comment]
Yea, I just noticed.. GMT vs local time.

There are some hacks involved there and I am vague on the history. I'd have to dig around.

**Comment by nyetwurk** [comment]
You may have to apply the user's "timezone" before doing those calculations. I dont recall the details which which one does what.

I think the db timestamps are in GMT, but php runs in localtime.

**Comment by nyetwurk** [comment]
As an aside: I really wish there was a better way to do UTC handling than running db queries in GMT. There probably is and I'm just a moron.

**Comment by nyetwurk** [comment]
here we go

in message.inc:

```
function process_message($user, &$msg)
{
    /* make a copy for comparison later */
    $omsg=$msg;

    /* FIXME: translate pid -> pmid */
    if (!isset($msg['pmid']) && isset($msg['pid']))
        $msg['pmid'] = $msg['pid'];

    /* msg['date'] is time local to user... strftime would normally be
       time local to PHP server */
    $msg['date'] = gen_date($user, $msg['unixtime']);
```

**Pull request merged**
