### PR TITLE
added chef and vagrant setup

### PR DESCRIPTION
**Pull request by rfackett**
refer to the ./chef/readme.md for details on how to use it.

if you want to be able to restore wayot from backup, contact me for the missing pieces/changes required.

### CODE REVIEW

**Comment by nyetwurk** [comment]
A few comments:

1) dos mode files - please use unix mode, and make sure all files have linefeeds
2) Need to make an easy way to sync your config generator with my actual sample config files... or every time i make a change I have to edit too many files.. Or maybe remove the sample config files, and make init.php generate config(s) for you when not using chef/vagrant

**Comment by rfackett** [comment]
@nyetwurk I use Atom and it is set for Unix line endings (LF) via the line-endings package.

When not using chef/vagrant, the config files that need to be modified (setup and config) are not changed at all (since no chef run happened).  So your sample files would persist as-is.  But if you want to move all config file changes into chef, I am happy to do that?  I just need to know what files you edit and what values you use (the value would become an attribute, so you would change everything in 1 file (./chef/attributes/default.rb) as opposed to each file.

**Comment by nyetwurk** [comment]
Actually, the generator should make apache.conf, setup-local.conf and config-local.conf.

The generators should NEVER touch files that are under revision control - the point of the -local.conf is so you can override the checked in defaults.

**Comment by rfackett** [comment]
moving from wayot thread.  So you want to create a customized:

- apache.conf
- setup-local.conf
- config-local.conf

using something that is platform independent? I assume it would be bash or PHP?  I guess we could have a bash script that replicates what chef does using the same values in ./chef/attributes.default.rb .  Does that sound like what you want?

**Comment by nyetwurk** [comment]
Yes! Exactly this. Note that the local config files are very short and only contain overrides.

**Comment by rfackett** [comment]
one point of clarification before I update and resubmit, you want a complete setup-local.conf / config-local.conf that have values from the attributes file, not files with only the changed values correct?

so setup.conf and config.conf will look like they do in github, but setup-local.conf and config-local.conf will look like they do after a chef build?

**Comment by nyetwurk** [comment]
No, they should ONLY contain customizations, they should not be a copy

eg:
```
<?php
$create_disabled = 1;
$login_to_read = 1;
$domain = "forum.org";
$default_page = "/other/";
?>
```
The whole point is to not burden the end user with worrying about anything but the things they want different from default..

**Comment by nyetwurk** [comment]
eg config-local.inc:

```
<?php
$sql_username = "xxx";
$sql_password = "xxx";
$bounce_host = "forum.org";
$cookie_host = array(".forum.org",".forum.net");
$p2f_address["other"] = "xxx@phone2forum.com";
$p2f_address["test"] = "xxxtest@phone2forum.com";
$imgur_client_id = "xxx";
$imgur_client_secret = "xxx";
?>
```

**Pull request closed without merging**
